### ISSUE TITLE
Plugin not work

### ISSUE THREAD

**Issue by gurudlan** [GenuinelyOptimistic/pay-woocommerce-plugin#1]
Hi,

after installing your plugin, set up API key(it's Client id?) and trans. key(it's Client Secret?) i make test and plugin redirect to localhost:90/epay... 
Hm, i mean you forgot your local testing settings in master release...

For API and trans key i mean, i have this options in my acc.
Test GoID
Test SecureKey
Test ClientID
Test ClientSecret

Which is your API and transaction key?

Thank you

**Comment by denzildoyle** [comment]
Hi @gurudlan 

Thank you for trying my plugin. However this plugin is still being developed and it's specifically being developed for use with [GOPay ](http://www.gopaytt.com/ ) which is also still under development.
